#!/usr/bin/env bash

set -euo pipefail

if [[ -d src/ ]]; then

  printf "Building src/\n"

  mkdir -p dst/lib/

  find src/ -type f -name "*.java" > sources.txt

  if [[ "${MODE:-development}" == production ]]; then

    javac -cp "dst/lib/*" @sources.txt -d dst/lib/

  else

    javac -cp "dst/lib/*" @sources.txt -d dst/lib/ -g
 
  fi

  jar cf dst/lib/mywebappserver.jar -C dst/lib/ com/

  rm -r dst/lib/com/

  rm sources.txt

fi

printf "Done\n"

